int inputCollegeInfo(char * filename,College x[]);
int inputSexInfo(char * filename,Sex x[]);
int inputStudentInfo(char * filename,Student x[]);
void menu(enum menu_type m_type);
int check_pwd(char * pwd);
int base64_encode(const char *indata, int inlen, char *outdata, int *outlen);
static char cmove_bits(unsigned char src, unsigned lnum, unsigned rnum); 
void print_table(int n,char c);
void countAvg(Student x[],int num);
void showMsg(char * msg);
